# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: 🔨 Build Project
        uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'
      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: ls -lah *
      - name: 🔨 Build Sync
        run: |
          node sync/sync.js
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "hallo"
        env:
          host: davida.ch-dns.net
          user: ${{ secrets.ftp_user_davida }}
          password: ${{ secrets.ftp_password_davida }}
          localRoot: ./dist/
          include: '{"*" , ".*"}'                
          exclude: '{"thumbs/*", "qr/*" }'                                                                   
          # delete ALL existing files at destination before uploading, if true   
          deleteRemote: false                                
          forcePasv: true     
          sftp: false  

         
